import { BaseEntity } from './../../shared';

export class Signalling implements BaseEntity {
    constructor(
        public id?: number,
        public pdate?: any,
        public startTime?: number,
        public endTime?: number,
        public interfaceType?: string,
        public cell?: number,
        public imei?: number,
        public imsi?: number,
        public appType?: number,
        public appStatus?: number,
        public protocolType?: number,
        public appSubType?: number,
        public ulData?: number,
        public dlData?: number,
        public lastHttpResponseDelay?: number,
        public procedureType?: number,
        public procedureStatus?: number,
        public cause?: number,
        public keyword?: number,
        public targetCellid?: number,
        public csfbIndication?: number,
        public reqCauseType?: number,
        public reqCause?: number,
        public failureCauseType?: number,
        public failureCause?: number,
        public errorCauseType?: number,
        public errorCause?: number,
        public hoCancelCauseType?: number,
        public hoCancelCause?: number,
        public rowCount?: number,
        public servingRsrp?: number,
        public servingRsrpAvg?: number,
        public servingRsrpStdDev?: number,
        public servingRsrq?: number,
        public servingRsrqAvg?: number,
        public servingRsrqStdDev?: number,
        public aoa?: number,
        public aoaAvg?: number,
        public aoaStdDev?: number,
        public ta?: number,
        public taAvg?: number,
        public taStdDev?: number,
        public ulSinr?: number,
        public ulSinrAvg?: number,
        public ulSinrStdDev?: number,
        public enbReceivedPower?: number,
        public enbReceivedPowerAvg?: number,
        public enbReceivedPowerStdDev?: number,
        public phr?: number,
        public phrAvg?: number,
        public phrStdDev?: number,
    ) {
    }
}
