import { BaseEntity } from './../../shared';

export class Uu implements BaseEntity {
    constructor(
        public id?: number,
        public pdate?: any,
        public phour?: number,
        public cell?: string,
        public imei?: string,
        public imsi?: string,
        public rrcConnectRequest?: number,
        public rrcConnectSuccess?: number,
        public rrcConnectSuccessRate?: number,
        public rrcReconfigRequest?: number,
        public rrcReconfigSuccess?: number,
        public rrcReconfigSuccessRate?: number,
        public rrcReconstructionRequest?: number,
        public rrcReconstructionSuccess?: number,
        public rrcReconstructionSuccessRate?: number,
        public rrcReleaseRequest?: number,
        public rrcReleaseSuccess?: number,
        public rrcReleaseSuccessRate?: number,
        public smActivateRequest?: number,
        public smActivateSuccess?: number,
        public smActivateSuccessRate?: number,
        public cellInterHandoverRequest?: number,
        public cellInterHandoverSuccess?: number,
        public cellInterHandoverSuccessRate?: number,
        public stationIntraHandoverRequest?: number,
        public stationIntraHandoverSuccess?: number,
        public stationIntraHandoverSuccessRate?: number,
        public stationInterHandoverRequest?: number,
        public stationInterHandoverSuccess?: number,
        public stationInterHandoverSuccessRate?: number,
        public ratInRequest?: number,
        public ratInSuccess?: number,
        public ratInSuccessRate?: number,
        public ratOutRequest?: number,
        public ratOutSuccess?: number,
        public ratOutSuccessRate?: number,
        public psPagingRequest?: number,
        public psPagingSuccess?: number,
        public psPagingSuccessRate?: number,
        public csPagingRequest?: number,
        public csPagingSuccess?: number,
        public csPagingSuccessRate?: number,
        public othereventRequest?: number,
        public othereventSuccess?: number,
        public othereventSuccessRate?: number,
    ) {
    }
}
