import { BaseEntity } from './../../shared';

export class Uhttp implements BaseEntity {
    constructor(
        public id?: number,
        public pdate?: any,
        public phour?: number,
        public cell?: string,
        public imei?: string,
        public imsi?: string,
        public flowSum?: number,
        public rateFlowRate?: number,
        public rateFlowSuccessRate?: number,
        public rateFlowSuccessDRate?: number,
        public rateFlow?: number,
        public rateFlowRequest?: number,
        public rateFlowBpSpeed?: number,
        public rateFlowBpSpeedDRate?: number,
        public rateFlowSpDelay?: number,
        public rateFlowSpDelayDRate?: number,
        public delayFlowRate?: number,
        public delayFlowSuccessRate?: number,
        public delayFlowSuccessDRate?: number,
        public delayFlow?: number,
        public delayFlowRequest?: number,
        public delayFlowBpSpeed?: number,
        public delayFlowBpSpeedDRate?: number,
        public delayFlowSpDelay?: number,
        public delayFlowSpDelayDRate?: number,
        public refreshFlowRate?: number,
        public refreshFlowSuccessRate?: number,
        public refreshFlowSuccessDRate?: number,
        public refreshFlow?: number,
        public refreshFlowRequest?: number,
        public refreshFlowBpSpeed?: number,
        public refreshFlowBpSpeedDRate?: number,
        public refreshFlowSpDelay?: number,
        public refreshFlowSpDelayDRate?: number,
        public instantFlowRate?: number,
        public instantFlowSuccessRate?: number,
        public instantFlowSuccessDRate?: number,
        public instantFlow?: number,
        public instantFlowRequest?: number,
        public instantFlowBpSpeed?: number,
        public instantFlowBpSpeedDRate?: number,
        public instantFlowSpDelay?: number,
        public instantFlowSpDelayDRate?: number,
        public tcpCreactlinkDelay?: number,
        public tcpCreactlinkCount?: number,
        public tcpCreactlinkResponseDelay?: number,
        public tcpCreactlinkResponseCount?: number,
        public tcpCreactlinkConfirmDelay?: number,
        public tcpCreactlinkConfirmCount?: number,
        public bpFlow?: number,
        public bpDelay?: number,
        public serviceRequest?: number,
        public serviceSuccess?: number,
        public tencentVideoServiceRequest?: number,
    ) {
    }
}
